pipeline {
         agent any
         stages {
                 stage('build stage') {
                 steps {
                     sh 'cd eureka-server && mvn clean install'
                     echo 'Building Spring Boot application '
                 }
                 }
                 stage('build docker image stage ') {
                 steps {
                    sh 'cd eureka-server && docker build -t eureka-server .'
                    echo 'Building docker image'
                 }
                 }
         }
}
