FROM openjdk:8-jdk-alpine
MAINTAINER Skander MEZIANE <meziane.skander05@gmail.com> 
ADD target/product-catalog-service.jar product-catalog-service.jar
ENTRYPOINT ["java", "-jar", "/product-catalog-service.jar"]
EXPOSE 6666
