FROM openjdk:8-jdk-alpine
MAINTAINER Skander MEZIANE <meziane.skander05@gmail.com>
ADD target/product-recommendation-service.jar product-recommendation-service.jar
ENTRYPOINT ["java", "-jar", "/product-recommendation-service.jar"]
EXPOSE 7777
