pipeline {
         agent any
         stages {
                 stage('build stage') {
                 steps {
                     sh 'cd user-service && mvn clean install'
                     echo 'Building Spring Boot application '
                 }
                 }
                 stage('build docker image stage ') {
                 steps {
                    sh 'docker build -t .'
                    echo 'Building docker image'
                 }
                 }
         }
}
